# Expects:
#   cc.*, device_ip, bdos: { name, bandwidth_in, bandwidth_out, action, protect.* }

- name: "Create BDOS profile {{ bdos.name }} on {{ device_ip }}"
  create_bdos_profile:
    provider:
      server: "{{ cc.server }}"
      username: "{{ cc.username }}"
      password: "{{ cc.password }}"
      verify_ssl: "{{ cc.verify_ssl | default(false) }}"
    device_ip: "{{ device_ip }}"
    profile:
      name: "{{ bdos.name }}"
      action: "{{ bdos.action }}"
      bandwidth_in: "{{ bdos.bandwidth_in }}"
      bandwidth_out: "{{ bdos.bandwidth_out }}"
      protect: "{{ bdos.protect }}"
