---
- name: Create network class only
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
  vars:
    device_ip: "10.105.192.32"
    netclass:
      name: "egor_test_net"
      groups:
        - { address: "10.10.10.0", mask: "255.255.255.0" }
        - { address: "10.10.11.0", mask: "255.255.255.0" }

  tasks:
    - name: Lock device
      dp_lock:
        provider: "{{ cc }}"
        device_ip: "{{ device_ip }}"

    - name: Create network groups in class {{ netclass.name }}
      create_network_class:
        provider: "{{ cc }}"
        device_ip: "{{ device_ip }}"
        class_name: "{{ netclass.name }}"
        address: "{{ item.address }}"
        mask: "{{ item.mask }}"
        index: "{{ idx }}"
      loop: "{{ netclass.groups }}"
      loop_control:
        index_var: idx
        label: "{{ item.address }}/{{ item.mask }}"
        
    - name: Unlock device
      dp_unlock:
        provider: "{{ cc }}"
        device_ip: "{{ device_ip }}"
