---
- name: Create Traffic Filter profiles and protections
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
    - ../vars/create_vars.yml

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
          when: not (skip_device_lock | default(false))

        - name: Configure Traffic Filter profiles and protections
          create_traffic_filter:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
            tf_profiles: "{{ tf_profiles | default([]) }}"
            tf_protections: "{{ tf_protections | default([]) }}"
          loop: "{{ dp_ip }}"
          loop_control:
            label: "Device: {{ item }}"
          register: tf_create_results

        - name: Display TF creation results (formatted)
          vars:
            formatted_output: |
              Device: {{ item.item }}
              {% if item.failed | default(false) %}
              Error occurred during creation:
                - {{ item.msg | default('Unknown error') }}
              {% else %}
              Traffic Filter Configurations created successfully:
              {% if item.debug_info.input.profiles_count | default(0) > 0 %}
                - {{ item.debug_info.input.profiles_count }} profile(s) created
              {% endif %}
              {% if item.debug_info.input.protections_count | default(0) > 0 %}
                - {{ item.debug_info.input.protections_count }} protection(s) created
              {% endif %}
              {% endif %}
          debug:
            msg: "{{ formatted_output.split('\n') }}"
          loop: "{{ tf_create_results.results }}"
          loop_control:
            label: "Device: {{ item.item }}"

        - name: Apply policy updates per device
          update_policies:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
          loop_control:
            label: "Applying policies: {{ item }}"
          when:
            - not (skip_policy_updates | default(false))
            - tf_create_results is defined
            - tf_create_results.changed | default(false)

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
          when: not (skip_device_lock | default(false))
