---
- name: Apply policies by device map
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
    - ../vars/policies.yml
    - ../vars/device_map.yml

  tasks:
    - name: Build policy lookup
      set_fact:
        policy_by_name: "{{ dict(policies | map(attribute='name') | zip(policies)) }}"

    - name: Iterate devices
      loop: "{{ device_policy_map | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      vars:
        device_ip: "{{ item.key }}"
        policy_names: "{{ item.value }}"
      block:
        - name: Apply each policy to device
          include_role:
            name: policy
          loop: "{{ policy_names }}"
          loop_control:
            loop_var: policy_name
          vars:
            policy: "{{ policy_by_name[policy_name] }}"
            device_ip: "{{ device_ip }}"
