---
- name: Create Traffic Filter profiles and protections
  hosts: cc
  gather_facts: false
  vars_files:
    - ../vars/cc.yml
    - ../vars/create_vars.yml

  tasks:
    - name: Create and apply Traffic Filter configuration
      block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
          when: not (skip_device_lock | default(false))

        - name: Configure Traffic Filter profiles and protections
          create_traffic_filter:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
            tf_profiles: "{{ create_tf_profiles | default([]) }}"
            tf_protections: "{{ create_tf_protections | default([]) }}"
          loop: "{{ dp_ip }}"
          loop_control:
            label: "Device: {{ item }}"
          register: tf_create_results

        # --- USER-FRIENDLY DISPLAY TASK ---
        - name: Display Traffic Filter creation results
          vars:
            formatted_output: |
              **Device: {{ item.item }}**

              EXECUTION RESULTS:

              **Traffic Filter Profiles created successfully:**
              {{ item.response.pretty_profiles }}

              **Traffic Filter Protections created successfully:**
              {{ item.response.pretty_protections }}

              **Errors Detected:**
              {% if item.response.errors | length > 0 %}
              - {{ item.response.errors | join('\n- ') }}
              {% else %}
              No errors detected.
              {% endif %}
          debug:
            msg: "{{ formatted_output.split('\n') }}"
          loop: "{{ tf_create_results.results }}"
          loop_control:
            label: "Device: {{ item.item }}"

        # --- NEW API DEBUG DISPLAY TASK ---
        - name: Display API Transaction Details (DEBUG)
          when: item.response.debug_info is defined and item.response.debug_info | length > 0
          vars:
            api_debug_output: |
              {% for info in item.response.debug_info %}
              --------------------------------------------------
              **API TRANSACTION:** {{ loop.index }}
              **METHOD:** {{ info.method | default('N/A') }}
              **URI:** {{ info.uri | default('N/A') }}
              **Response Code:** {{ info.response_code | default('N/A') }}
              {% if info.body is defined %}
              **BODY:**
              {{ info.body | to_nice_json(indent=4) }}
              {% endif %}
              **Response Body (Partial/Raw):**
              {% if info.response_body is defined %}
              {{ info.response_body | to_nice_json(indent=4) }}
              {% else %}
              N/A or not logged.
              {% endif %}
              {% endfor %}

          ansible.builtin.debug:
            msg: |
              ==================================================
              API DEBUG INFO FOR DEVICE: {{ item.item }}
              {{ api_debug_output }}
              ==================================================
              
          loop: "{{ tf_create_results.results }}"
          loop_control:
            label: "Device API Debug: {{ item.item }}"

        - name: Apply policy updates per device
          update_policies:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
          loop_control:
            label: "Applying policies: {{ item }}"
          when:
            - not (skip_policy_updates | default(false))
            - tf_create_results is defined
            - tf_create_results.changed | default(false)

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
          when: not (skip_device_lock | default(false))