---
- name: Example workflow - Get current state then edit network class groups
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
  vars:
    dp_ip: "10.105.192.32"
    target_class_name: "egor_test_net"

  tasks:
    - name: Get current network class structure
      get_network_class:
        provider: "{{ cc }}"
        dp_ip: "{{ dp_ip }}"
        filter_class_name: "{{ target_class_name }}"
      register: current_state

    - name: Display current network class groups
      debug:
        msg: "Current network class has {{ current_state.response | length }} groups"

    - name: Show detailed current state
      debug:
        var: current_state.response

    - name: Lock device
      dp_lock:
        provider: "{{ cc }}"
        dp_ip: "{{ dp_ip }}"

    - name: Edit specific network class group (modify index 2)
      edit_network_class:
        provider: "{{ cc }}"
        dp_ip: "{{ dp_ip }}"
        class_name: "{{ target_class_name }}"
        index: 2
        address: "155.1.229.0"
        mask: "27"
      register: edit_result

    - name: Display edit result
      debug:
        var: edit_result

    - name: Unlock device
      dp_unlock:
        provider: "{{ cc }}"
        dp_ip: "{{ dp_ip }}"

    - name: Get updated network class structure
      get_network_class:
        provider: "{{ cc }}"
        dp_ip: "{{ dp_ip }}"
        filter_class_name: "{{ target_class_name }}"
      register: updated_state

    - name: Show updated state
      debug:
        var: updated_state.response
