---
- name: Edit Traffic Filter profiles and protections
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
    - ../vars/edit_vars.yml

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
          when: not (skip_device_lock | default(false))

        - name: Edit traffic filter profiles/protections
          edit_traffic_filter:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
            traffic_filters: "{{ traffic_filters }}"
          loop: "{{ dp_ip }}"
          loop_control:
            label: "Device: {{ item }}"
          register: tf_edit_results

        - name: Display Traffic Filter edit results (formatted)
          vars:
            formatted_output: |
              Device: {{ item.item }}
              {% if item.failed | default(false) %}
              Error: {{ item.msg | default('Unknown error') }}
              {% else %}
              Edited Profiles: {{ item.response.edited_profiles | length }}
              Edited Protections: {{ item.response.edited_protections | length }}
              {% endif %}
          debug:
            msg: "{{ formatted_output.split('\n') }}"
          loop: "{{ tf_edit_results.results }}"
          loop_control:
            label: "Device: {{ item.item }}"

        - name: "Apply policy updates per device"
          update_policies:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
          loop_control:
            label: "Applying policies: {{ item }}"
          when:
            - not (skip_policy_updates | default(false))
            - tf_edit_results is defined
            - tf_edit_results.changed | default(false)

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
          when: not (skip_device_lock | default(false))
