name: Mirror to Radware

on:
  push:
    branches:
      - '**'
  delete:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: Mirror branches to radware/dp_config_builder
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        if: github.event_name == 'push'
          
      - name: Setup SSH
        if: github.event_name == 'push'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
      - name: Configure Git
        if: github.event_name == 'push'
        run: |
          git config user.name "GitHub Actions Mirror Bot"
          git config user.email "actions@github.com"
          git config core.sshCommand "ssh -i ~/.ssh/deploy_key -o IdentitiesOnly=yes"
          
      - name: Mirror branch to radware
        if: github.event_name == 'push'
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Mirroring branch: $BRANCH_NAME"
          
          git remote add radware git@github.com:Radware/dp_config_builder.git
          
          git push radware HEAD:${BRANCH_NAME} --force
          
      - name: Delete branch from radware
        if: github.event_name == 'delete'
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          BRANCH_NAME="${{ github.event.ref }}"
          echo "Deleting branch: $BRANCH_NAME"
          
          # Use curl to delete via GitHub API (doesn't need git repo)
          curl -X DELETE \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Radware/dp_config_builder/git/refs/heads/${BRANCH_NAME}
          
          echo "Branch deletion request sent"
