name: Mirror to Radware

on:
  push:
    branches:
      - '**'
  delete:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: Mirror branches to radware/dp_config_builder
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Mirror Bot"
          git config user.email "actions@github.com"
          git config core.sshCommand "ssh -i ~/.ssh/deploy_key -o IdentitiesOnly=yes"
          
      - name: Mirror branch to radware
        if: github.event_name == 'push'
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Mirroring branch: $BRANCH_NAME"
          
          # Use SSH URL instead of HTTPS
          git remote add radware git@github.com:Radware/dp_config_builder.git
          
          git push radware HEAD:${BRANCH_NAME} --force
          
      - name: Delete branch from radware
        if: github.event_name == 'delete'
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Deleting branch: $BRANCH_NAME"
          
          # Use SSH for deletion
          GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key -o IdentitiesOnly=yes" \
          git push git@github.com:Radware/dp_config_builder.git --delete ${BRANCH_NAME}
