name: Mirror to Radware

on:
  push:
    branches:
      - '**'
  delete:
    branches:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: Mirror branches to radware/dp_config_builder
    
    steps:
      - name: Checkout repository
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        if: github.event_name == 'push'
        run: |
          git config user.name "GitHub Actions Mirror Bot"
          git config user.email "actions@github.com"
          
      - name: Mirror branch to radware
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Mirroring branch: $BRANCH_NAME (excluding .github/workflows)"
          
          # Create a clean branch without workflows
          git checkout -b temp-mirror-$GITHUB_SHA
          
          # Remove workflows directory
          rm -rf .github/workflows
          
          # If .github is now empty, remove it
          if [ -d .github ] && [ -z "$(ls -A .github)" ]; then
            rm -rf .github
          fi
          
          # Commit the removal (only if there are changes)
          git add -A
          git diff --staged --quiet || git commit -m "Exclude workflows for mirror"
          
          # Add remote and push using token
          git remote add radware https://x-access-token:${GITHUB_TOKEN}@github.com/Radware/dp_config_builder.git
          git push radware temp-mirror-$GITHUB_SHA:${BRANCH_NAME} --force
          
          echo "✓ Branch mirrored successfully"
          
      - name: Delete branch from radware
        if: github.event_name == 'delete'
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          BRANCH_NAME="${{ github.event.ref }}"
          echo "Deleting branch: $BRANCH_NAME"
          
          # Use GitHub API for deletion
          RESPONSE=$(curl -s -w "\n%{http_code}" -X DELETE \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Radware/dp_config_builder/git/refs/heads/${BRANCH_NAME})
          
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo "----------------------------------------"
          echo "HTTP Status: $HTTP_CODE"
          echo "Response: $BODY"
          echo "----------------------------------------"
          
          if [ "$HTTP_CODE" = "204" ]; then
            echo "✓ Branch deleted successfully"
            exit 0
          elif [ "$HTTP_CODE" = "404" ]; then
            echo "✓ Branch already deleted or doesn't exist"
            exit 0
          elif [ "$HTTP_CODE" = "401" ]; then
            echo "✗ Authentication failed - check MIRROR_TOKEN"
            exit 1
          elif [ "$HTTP_CODE" = "403" ]; then
            echo "✗ Permission denied - token lacks permissions"
            exit 1
          else
            echo "✗ Unexpected error (HTTP $HTTP_CODE)"
            exit 1
          fi
