name: Mirror to Radware

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch
  delete:
    branches:
      - '**'  # Trigger on branch deletion

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: Mirror branches to radware/dp_config_builder
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Mirror Bot"
          git config user.email "actions@github.com"
          
      - name: Mirror branch to radware
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          # Extract branch name
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Mirroring branch: $BRANCH_NAME"
          
          # Add radware remote
          git remote add radware https://x-access-token:${GITHUB_TOKEN}@github.com/Radware/dp_config_builder.git
          
          # Push the branch
          git push radware HEAD:${BRANCH_NAME} --force
          
      - name: Delete branch from radware
        if: github.event_name == 'delete'
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          # Extract branch name from the event
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Deleting branch: $BRANCH_NAME"
          
          # Delete the branch on radware
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/Radware/dp_config_builder.git --delete ${BRANCH_NAME}
